version: "2"
name: POC
canonical: poc
author: Ravichandran Somasundaram
status: private
description: Cloud-ui-poc
image: ""
keywords:
- Something
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      poc:
        destination: ($ project $)/default/terraform/($ environment $)/poc.tf
        path: default/terraform/poc.tf.sample
